version: '3.8'
services:
  # customer-service:
  #   container_name: customer-service
  #   image: customer-service
  #   build:
  #     context: .    
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:8083"
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/customer_db
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=root
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  mysql:
    image: mysql:8.0.42
    container_name: customer-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customer_db
      - MYSQL_USER=demouser
      - MYSQL_PASSWORD=demopassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local


