# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: Customer
  datasource:
    url: jdbc:mysql://localhost:3308/customer_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenthaingoc2733@gmail.com
    password: cwhncnhmijxmtflg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF        
    com:
      ecommerce: DEBUG
