openapi: 3.0.1
info:
  title: User API
  version: 1.0.0
  description: API to manage users in the system

servers:
  - url: http://localhost:8084
    description: Local server

paths:
  /api/v1/users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User' 

components:
  schemas:
    User:
      type: object
      required:
        - username
        - password
        - email
        - birthday
        - address
      properties:
        id:
          type: integer
          description: The user ID
          example: 1
        username:
          type: string
          description: The user name
          example: John Doe
        password:
          type: string
          description: The user password
          example: password123
        email:
          type: string
          description: The user email
        birthday:
          type: string
          format: date
          description: The user birthday
          example: 1990-01-01
        address:
          type: string
          description: The user address
          example: 123 Main St
        created_at:
          type: string
          format: date-time
          description: The date the user was created
          example: 2022-01-01T00:00:00Z
        updated_at:
          type: string
          format: date-time
          description: The date the user was last updated
          example: 2022-01-01T00:00:00Z
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: The error code
          example: 400
        message:
          type: string
          description: The error message
          example: Bad Request





